services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "2"
          memory: 2G

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  engine-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: local_server
    env_file:
      - .env
    ports:
      - 3005:3005
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    # volumes:
    # - ./:/app
    # - node_modules:/app/node_modules

  engine-worker:
    build:
      dockerfile: Dockerfile
      context: .
      target: local_worker
    env_file:
      - .env
    ports:
      - 3006:3006
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    # volumes:
    # - ./:/app
    # - node_modules:/app/node_modules

volumes:
  # node_modules:
  db_data:
  pgadmin:
