version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web3-api:
    build:
      context: .
    image: thirdweb/web3-api:0.1.0
    ports:
      - 5432:5432

volumes:
  db_data:
