version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  swaggerui:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 3015:8080
    environment:
      SWAGGER_JSON: /app/swagger.yml
    volumes:
      - ./swagger.yml:/app/swagger.yml

volumes:
  db_data:
  pgadmin:
