name: Build on beta branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: beta # checkout the main branch to build nightly

      - name: Check Disk Space Before Build
        run: df -h

      - name: Docker Prune
        run: docker system prune -af

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thirdweb/engine:beta-nightly
          build-args: |
            ENGINE_VERSION=beta-nightly

      - name: Check Disk Space After Build
        run: df -h
