name: Run E2E Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Use Node.js 18.15.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: make test
