name: Tag Based Image Build

on:
  create:

jobs:
  buildImageForNewTag:
    if: startsWith(github.ref, 'refs/tags/') # Only run this job when a tag is created
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag name
        id: get_tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Determine Branch Name
        id: get_branch
        run: |
          branch=$(git branch -r --contains tags/${{ env.TAG_NAME }} | grep 'origin/' | sed 's|origin/||' | head -n 1)
          echo "BRANCH_NAME=$branch" >> $GITHUB_ENV

      - name: Check Disk Space Before Build
        run: df -h

      - name: Docker Prune
        run: docker system prune -af

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            thirdweb/engine:${{ env.TAG_NAME }}
            ${{ env.BRANCH_NAME == 'main' && 'thirdweb/engine:latest' }}
          build-args: |
            ENGINE_VERSION=${{ env.TAG_NAME }}

      - name: Check Disk Space After Build
        run: df -h
