name: Tag Based Image Build

on:
  release:
    types: [created] # This listens to release creation events

jobs:
  buildImageForNewBranch:
    if: startsWith(github.ref, 'refs/tags/') // This will run the workflow only when a tag is created
    runs-on: ubuntu-latest

    steps:
      - name: Check Disk Space Before Build
        run: df -h

      - name: Docker Prune
        run: docker system prune -af

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Fetches the branch at which the release was made
          ref: ${{ github.event.release.target_commitish }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            thirdweb/engine:${{ github.event.release.tag_name }}
            ${{ github.event.release.target_commitish == 'main' && 'thirdweb/engine:latest' }}
          build-args: |
            ENGINE_VERSION=${{ github.event.release.tag_name }}

      - name: Check Disk Space After Build
        run: df -h
